# Generated by Django 5.2.11 on 2026-04-13 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0011_rename_organizations_organizatio_type_idx_organizatio_organiz_d4294a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('esg_summary', 'ESG Summary'), ('framework', 'Framework'), ('group', 'Group ESG'), ('gap', 'Compliance Gap'), ('partner', 'Partner')], db_index=True, help_text='Type of report', max_length=50)),
                ('partner_type', models.CharField(choices=[('deg', 'Deutsche Entwicklungsgesellschaft'), ('usaid', 'USAID'), ('gcf', 'Green Climate Fund'), ('frc', 'Facility for Recovery and Climate'), ('none', 'Internal Only')], default='none', help_text='Partner type (for partner reports)', max_length=20)),
                ('reporting_period_id', models.UUIDField(blank=True, help_text='Reporting period ID for this report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Generation status', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='URL to download generated report (PDF/CSV/JSON)', null=True)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='json', help_text='Export format', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Report metadata (filters, parameters, etc.)')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Summary statistics for quick access')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When report was generated')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When report data expires (cache invalidation)', null=True)),
                ('framework', models.ForeignKey(blank=True, help_text='Framework (for framework and partner reports)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='organizations.regulatoryframework')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who requested report generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_generated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization for which report was generated', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports_report',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', 'report_type'], name='reports_rep_organiz_bdc0af_idx'), models.Index(fields=['organization', 'generated_at'], name='reports_rep_organiz_f16dd2_idx'), models.Index(fields=['status', 'generated_at'], name='reports_rep_status_bf9961_idx')],
            },
        ),
    ]
