# Generated by assistant: initial migration for submissions
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_rename_regulatory_coverage_to_primary_reporting_focus"),
        ("accounts", "0006_rename_accounts_pa_user_created_idx_accounts_pa_user_id_080f49_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingPeriod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(db_index=True)),
                ("quarter", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("LOCKED", "Locked"), ("SUBMITTED", "Submitted")], default="OPEN", max_length=16, db_index=True)),
                ("opened_at", models.DateTimeField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="reporting_periods", to="organizations.organization"),
                ),
                (
                    "locked_by",
                    models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="periods_locked", to="accounts.user"),
                ),
            ],
            options={
                "db_table": "submissions_reportingperiod",
            },
        ),
        migrations.AddIndex(
            model_name="reportingperiod",
            index=models.Index(fields=["organization", "status"], name="submissions__org_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reportingperiod",
            unique_together={("organization", "year", "quarter")},
        ),
    ]
