# Generated by assistant: create DataSubmission model
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
        ("indicators", "0003_remove_source_frameworks"),
        ("organizations", "0003_rename_regulatory_coverage_to_primary_reporting_focus"),
        ("accounts", "0006_rename_accounts_pa_user_created_idx_accounts_pa_user_id_080f49_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value_number", models.FloatField(blank=True, null=True)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_boolean", models.NullBooleanField()),
                ("metadata", models.JSONField(default=dict, blank=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved")], default="DRAFT", max_length=16, db_index=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="submissions", to="organizations.organization"),
                ),
                (
                    "indicator",
                    models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="submissions", to="indicators.indicator"),
                ),
                (
                    "reporting_period",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="submissions", to="submissions.reportingperiod"),
                ),
                (
                    "facility",
                    models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="submissions", to="organizations.facility"),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="submissions_made", to="accounts.user"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="submissions_approved", to="accounts.user"),
                ),
            ],
            options={
                "db_table": "submissions_datasubmission",
            },
        ),
        migrations.AddIndex(
            model_name="datasubmission",
            index=models.Index(fields=["organization", "reporting_period"], name="submissions__org_period_idx"),
        ),
        migrations.AddIndex(
            model_name="datasubmission",
            index=models.Index(fields=["indicator"], name="submissions__indicator_idx"),
        ),
        migrations.AddIndex(
            model_name="datasubmission",
            index=models.Index(fields=["status"], name="submissions__status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="datasubmission",
            unique_together={("organization", "indicator", "reporting_period", "facility")},
        ),
    ]
