# Generated by Django 5.2.11 on 2026-03-08 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('organizations', '0003_rename_regulatory_coverage_to_primary_reporting_focus'),
        ('submissions', '0002_create_datasubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Activity Submission',
                'verbose_name_plural': 'Activity Submissions',
                'db_table': 'submissions_activitysubmission',
            },
        ),
        migrations.RenameIndex(
            model_name='reportingperiod',
            new_name='submissions_organiz_a4fb79_idx',
            old_name='submissions__org_status_idx',
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_submissions', to='organizations.facility'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_submissions', to='submissions.reportingperiod'),
        ),
    ]
