# Generated by Django 5.2.11 on 2026-03-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_refactor_reporting_period_flexible_dates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportingperiod',
            new_name='submissions_organiz_6ac7d3_idx',
            old_name='submissions_org_period_type_idx',
        ),
        migrations.RenameIndex(
            model_name='reportingperiod',
            new_name='submissions_start_d_6b3eae_idx',
            old_name='submissions_start_end_date_idx',
        ),
    ]
