# Generated by Django 5.2.11 on 2026-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activitytype_data_type'),
        ('organizations', '0009_add_reporting_frequency'),
        ('submissions', '0006_remove_unit_from_activitysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='activitysubmission',
            unique_together={('organization', 'reporting_period', 'activity_type', 'facility')},
        ),
    ]
