# Generated by Django 5.2.11 on 2026-04-12 02:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0005_indicatorvalue'),
        ('organizations', '0011_rename_organizations_organizatio_type_idx_organizatio_organiz_d4294a_idx_and_more'),
        ('submissions', '0008_add_quarter_to_reportingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environmental_score', models.FloatField(help_text='Environmental pillar score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_score', models.FloatField(help_text='Social pillar score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('governance_score', models.FloatField(help_text='Governance pillar score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(help_text='Weighted average of E/S/G scores (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('environmental_weight', models.FloatField(default=0.4, help_text='Weight for environmental score (default 0.4)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('social_weight', models.FloatField(default=0.3, help_text='Weight for social score (default 0.3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('governance_weight', models.FloatField(default=0.3, help_text='Weight for governance score (default 0.3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this score was last calculated')),
                ('is_consolidated', models.BooleanField(db_index=True, default=False, help_text='True for group consolidation, False for individual organization')),
                ('is_dirty', models.BooleanField(default=False, help_text='Whether this score needs recalculation')),
                ('organization', models.ForeignKey(help_text='Organization being scored', on_delete=django.db.models.deletion.CASCADE, related_name='esg_scores', to='organizations.organization')),
                ('reporting_period', models.ForeignKey(help_text='Reporting period for this score', on_delete=django.db.models.deletion.CASCADE, related_name='esg_scores', to='submissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'ESG Score',
                'verbose_name_plural': 'ESG Scores',
                'db_table': 'esg_scoring_esg_score',
                'indexes': [models.Index(fields=['organization', 'reporting_period'], name='esg_scoring_organiz_e9eb28_idx'), models.Index(fields=['is_consolidated', 'reporting_period'], name='esg_scoring_is_cons_0fdaf1_idx')],
                'unique_together': {('organization', 'reporting_period')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='Calculated indicator score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('value', models.FloatField(blank=True, help_text='Actual reported value for the indicator', null=True)),
                ('target', models.FloatField(blank=True, help_text='Target value for the indicator', null=True)),
                ('baseline', models.FloatField(blank=True, help_text='Baseline value for comparison', null=True)),
                ('progress', models.FloatField(blank=True, help_text='Progress toward target (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('poor', 'Poor (0-25%)'), ('at_risk', 'At Risk (26-50%)'), ('on_track', 'On Track (51-75%)'), ('achieved', 'Achieved (76-100%)')], db_index=True, default='on_track', help_text='Status indicator (poor, at_risk, on_track, achieved)', max_length=20)),
                ('calculation_method', models.CharField(blank=True, help_text="Method used to calculate score (e.g., 'linear', 'weighted', 'custom')", max_length=50)),
                ('note', models.TextField(blank=True, help_text='Notes about the calculation or score')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this score was last calculated')),
                ('is_manual', models.BooleanField(default=False, help_text='Whether score was manually entered vs auto-calculated')),
                ('indicator', models.ForeignKey(help_text='Indicator being scored', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='indicators.indicator')),
                ('organization', models.ForeignKey(help_text='Organization being scored', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_scores', to='organizations.organization')),
                ('reporting_period', models.ForeignKey(help_text='Reporting period for this score', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_scores', to='submissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Indicator Score',
                'verbose_name_plural': 'Indicator Scores',
                'db_table': 'esg_scoring_indicator_score',
                'indexes': [models.Index(fields=['organization', 'reporting_period'], name='esg_scoring_organiz_874ac4_idx'), models.Index(fields=['indicator', 'reporting_period'], name='esg_scoring_indicat_fe97a5_idx'), models.Index(fields=['status', 'reporting_period'], name='esg_scoring_status_eab88c_idx')],
                'unique_together': {('organization', 'indicator', 'reporting_period')},
            },
        ),
        migrations.CreateModel(
            name='PillarScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillar', models.CharField(choices=[('environmental', 'Environmental (E)'), ('social', 'Social (S)'), ('governance', 'Governance (G)')], db_index=True, help_text='ESG Pillar: Environmental, Social, or Governance', max_length=20)),
                ('score', models.FloatField(help_text='Aggregated pillar score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('indicator_count', models.IntegerField(help_text='Number of indicators included in this pillar score')),
                ('on_track_count', models.IntegerField(default=0, help_text='Number of indicators on track')),
                ('at_risk_count', models.IntegerField(default=0, help_text='Number of indicators at risk')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this score was last calculated')),
                ('is_dirty', models.BooleanField(default=False, help_text='Whether this score needs recalculation')),
                ('organization', models.ForeignKey(help_text='Organization being scored', on_delete=django.db.models.deletion.CASCADE, related_name='pillar_scores', to='organizations.organization')),
                ('reporting_period', models.ForeignKey(help_text='Reporting period for this score', on_delete=django.db.models.deletion.CASCADE, related_name='pillar_scores', to='submissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Pillar Score',
                'verbose_name_plural': 'Pillar Scores',
                'db_table': 'esg_scoring_pillar_score',
                'indexes': [models.Index(fields=['organization', 'pillar', 'reporting_period'], name='esg_scoring_organiz_09f336_idx'), models.Index(fields=['pillar', 'reporting_period'], name='esg_scoring_pillar_0be475_idx')],
                'unique_together': {('organization', 'pillar', 'reporting_period')},
            },
        ),
    ]
