# Generated by Django 5.2.10 on 2026-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillarscore',
            name='pillar',
            field=models.CharField(choices=[('ENV', 'Environmental'), ('SOC', 'Social'), ('GOV', 'Governance')], db_index=True, help_text='ESG Pillar: Environmental (ENV), Social (SOC), or Governance (GOV)', max_length=8),
        ),
    ]
