# Generated by assistant - initial migration for indicators app
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_rename_regulatory_coverage_to_primary_reporting_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pillar', models.CharField(choices=[('ENV', 'Environmental'), ('SOC', 'Social'), ('GOV', 'Governance')], db_index=True, max_length=8)),
                ('data_type', models.CharField(choices=[('number', 'Number'), ('percent', 'Percent'), ('boolean', 'Boolean'), ('text', 'Text'), ('currency', 'Currency')], db_index=True, max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'indicators_indicator',
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='FrameworkIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_indicators', to='organizations.regulatoryframework')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_mappings', to='indicators.indicator')),
            ],
            options={
                'db_table': 'indicators_frameworkindicator',
                'verbose_name': 'Framework Indicator',
                'verbose_name_plural': 'Framework Indicators',
            },
        ),
        migrations.CreateModel(
            name='OrganizationIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_overrides', to='indicators.indicator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_indicators', to='organizations.organization')),
            ],
            options={
                'db_table': 'indicators_organizationindicator',
                'verbose_name': 'Organization Indicator',
                'verbose_name_plural': 'Organization Indicators',
            },
        ),
        migrations.AddField(
            model_name='organizationindicator',
            name='source_frameworks',
            field=models.ManyToManyField(blank=True, help_text="Optional: frameworks that caused this indicator to be included", related_name='organization_indicator_sources', to='organizations.regulatoryframework'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['pillar'], name='indicators_indicator_pillar_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['data_type'], name='indicators_indicator_datatype_idx'),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['is_active'], name='indicators_indicator_active_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['framework', 'is_required'], name='indicators_fi_fw_req_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkindicator',
            index=models.Index(fields=['framework', 'display_order'], name='indicators_fi_fw_order_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationindicator',
            index=models.Index(fields=['organization', 'is_active'], name='indicators_orgind_org_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkindicator',
            unique_together={('framework', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationindicator',
            unique_together={('organization', 'indicator')},
        ),
    ]
