# Generated by Django 5.2.10 on 2026-02-24 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='frameworkindicator',
            new_name='indicators__framewo_a34e98_idx',
            old_name='indicators_fi_fw_req_idx',
        ),
        migrations.RenameIndex(
            model_name='frameworkindicator',
            new_name='indicators__framewo_76a8ea_idx',
            old_name='indicators_fi_fw_order_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='indicators__pillar_b82627_idx',
            old_name='indicators_indicator_pillar_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='indicators__data_ty_98975f_idx',
            old_name='indicators_indicator_datatype_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='indicators__is_acti_42b024_idx',
            old_name='indicators_indicator_active_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationindicator',
            new_name='indicators__organiz_924e65_idx',
            old_name='indicators_orgind_org_active_idx',
        ),
        migrations.AlterField(
            model_name='frameworkindicator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationindicator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
