# Generated by assistant: remove source_frameworks M2M from OrganizationIndicator
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0002_rename_indicators_fi_fw_req_idx_indicators__framewo_a34e98_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationindicator",
            name="source_frameworks",
        ),
    ]
