# Generated by Django 5.2.11 on 2026-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_migrate_frameworkindicator_to_requirement_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='calculation_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='emission_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('INPUT', 'Input'), ('DERIVED', 'Derived')], db_index=True, default='INPUT', help_text='INPUT indicators store raw operational data; DERIVED indicators are calculated outputs.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['indicator_type'], name='indicators__indicat_c65770_idx'),
        ),
    ]
