# Generated by Django 5.2.10 on 2026-04-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_require_indicator'),
        ('indicators', '0005_indicatorvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='indicator',
            field=models.ForeignKey(help_text='The indicator that this activity type contributes to', on_delete=django.db.models.deletion.PROTECT, related_name='activity_types', to='indicators.indicator'),
        ),
    ]
