# Generated by Django 5.2.10 on 2026-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('boolean', 'Boolean'), ('text', 'Text'), ('count', 'Count')], db_index=True, default='number', max_length=20),
        ),
    ]
