# Generated by Django 5.2.11 on 2026-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activitytype_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='default_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], db_index=True, default='MONTHLY', max_length=20),
        ),
    ]
