# Generated by Django 5.2.10 on 2026-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'ordering': ['name'], 'verbose_name': 'Capability', 'verbose_name_plural': 'Capabilities'},
        ),
        migrations.RemoveIndex(
            model_name='rolecapability',
            name='roles_role__role_id_c77de7_idx',
        ),
        migrations.RemoveField(
            model_name='capability',
            name='pillar',
        ),
        migrations.AddField(
            model_name='rolecapability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='code',
            field=models.CharField(help_text='Unique capability code (e.g., manage_organization, submit_environmental)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['role', 'is_active'], name='roles_role__role_id_d06d44_idx'),
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['capability', 'is_active'], name='roles_role__capabil_50b850_idx'),
        ),
    ]
