# Generated by Django 5.2.11 on 2026-04-12 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0005_indicatorvalue'),
        ('organizations', '0011_rename_organizations_organizatio_type_idx_organizatio_organiz_d4294a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier within framework (e.g., GRI 305-1, IFRS S2-1)', max_length=100)),
                ('title', models.CharField(help_text='Short title of the requirement', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Detailed description of what's required")),
                ('pillar', models.CharField(choices=[('environmental', 'Environmental'), ('social', 'Social'), ('governance', 'Governance')], help_text='ESG pillar this requirement addresses', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this is a mandatory or recommended requirement')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], db_index=True, default='active', help_text='Status of the requirement (active/deprecated/archived)', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Priority level for display/sorting (higher = more important)')),
                ('guidance_url', models.URLField(blank=True, help_text='Link to framework documentation or guidance', max_length=500)),
                ('version', models.CharField(blank=True, help_text='Version of requirement (e.g., 2023, v2.0)', max_length=50)),
                ('framework', models.ForeignKey(help_text='The framework this requirement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='organizations.regulatoryframework')),
            ],
            options={
                'verbose_name': 'Framework Requirement',
                'verbose_name_plural': 'Framework Requirements',
                'db_table': 'compliance_framework_requirement',
                'ordering': ['framework__priority', 'pillar', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorFrameworkMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_type', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting'), ('reference', 'Reference')], default='primary', help_text='Type of mapping (primary/supporting/reference)', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary indicator for this requirement')),
                ('rationale', models.TextField(blank=True, help_text='Explanation of how indicator satisfies/addresses requirement')),
                ('coverage_percent', models.IntegerField(default=100, help_text='How much of the requirement is covered by this indicator (0-100%)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this mapping is active/current')),
                ('notes', models.TextField(blank=True, help_text='Additional notes on this mapping')),
                ('framework', models.ForeignKey(help_text='The framework this mapping relates to', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='organizations.regulatoryframework')),
                ('indicator', models.ForeignKey(help_text='The indicator being mapped', on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_requirement_mappings', to='indicators.indicator')),
                ('requirement', models.ForeignKey(help_text='The specific requirement being addressed', on_delete=django.db.models.deletion.CASCADE, related_name='indicator_mappings', to='compliance.frameworkrequirement')),
            ],
            options={
                'verbose_name': 'Indicator Framework Mapping',
                'verbose_name_plural': 'Indicator Framework Mappings',
                'db_table': 'compliance_indicator_framework_mapping',
                'ordering': ['-is_primary', '-mapping_type', '-coverage_percent'],
            },
        ),
        migrations.AddIndex(
            model_name='frameworkrequirement',
            index=models.Index(fields=['framework', 'pillar'], name='compliance__framewo_9e118f_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkrequirement',
            index=models.Index(fields=['framework', 'status'], name='compliance__framewo_f3ac29_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkrequirement',
            index=models.Index(fields=['pillar', 'status'], name='compliance__pillar_a3bdb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkrequirement',
            unique_together={('framework', 'code')},
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkmapping',
            index=models.Index(fields=['indicator', 'framework'], name='compliance__indicat_84907d_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkmapping',
            index=models.Index(fields=['framework', 'is_active'], name='compliance__framewo_eb71a8_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkmapping',
            index=models.Index(fields=['requirement', 'is_active'], name='compliance__require_de1ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorframeworkmapping',
            index=models.Index(fields=['indicator', 'is_active'], name='compliance__indicat_04f9dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicatorframeworkmapping',
            unique_together={('indicator', 'framework', 'requirement')},
        ),
    ]
