# Generated by Django 5.2.11 on 2026-04-13 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0011_rename_organizations_organizatio_type_idx_organizatio_organiz_d4294a_idx_and_more'),
        ('submissions', '0008_add_quarter_to_reportingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkrequirement',
            name='pillar',
            field=models.CharField(choices=[('ENV', 'Environmental'), ('SOC', 'Social'), ('GOV', 'Governance')], help_text='ESG pillar this requirement addresses', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplianceGapPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandatory_weight', models.FloatField(default=0.0, help_text='Weight from mandatory requirement (0-40)')),
                ('framework_weight', models.FloatField(default=0.0, help_text='Weight from framework priority (0-30)')),
                ('pillar_weight', models.FloatField(default=0.0, help_text='Weight from pillar importance (0-20)')),
                ('coverage_impact_weight', models.FloatField(default=0.0, help_text='Weight from coverage impact (0-10)')),
                ('priority_score', models.FloatField(default=0.0, help_text='Total priority score (0-100)')),
                ('priority_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, help_text='High/Medium/Low priority', max_length=20)),
                ('impact_category', models.CharField(choices=[('direct', 'Direct Impact'), ('indirect', 'Indirect Impact'), ('strategic', 'Strategic')], default='direct', help_text='Type of impact if not addressed', max_length=20)),
                ('gap_description', models.TextField(blank=True, help_text='Why this requirement is not covered')),
                ('efforts_to_close', models.CharField(blank=True, help_text="What's needed to close this gap", max_length=255)),
                ('estimated_effort_days', models.IntegerField(default=0, help_text='Estimated effort to address gap (days)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this gap should be actively monitored')),
                ('last_assessed_at', models.DateTimeField(auto_now=True, help_text='When this gap priority was last calculated')),
                ('framework', models.ForeignKey(help_text='Framework containing the requirement', on_delete=django.db.models.deletion.CASCADE, related_name='prioritized_gaps', to='organizations.regulatoryframework')),
                ('organization', models.ForeignKey(help_text='Organization with compliance gap', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gaps', to='organizations.organization')),
                ('requirement', models.ForeignKey(help_text='Uncovered framework requirement', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gaps', to='compliance.frameworkrequirement')),
            ],
            options={
                'verbose_name': 'Compliance Gap Priority',
                'verbose_name_plural': 'Compliance Gap Priorities',
                'db_table': 'compliance_gap_priority',
                'ordering': ['-priority_score', 'priority_level', 'framework__priority'],
                'indexes': [models.Index(fields=['organization', 'priority_level'], name='compliance__organiz_5c1d44_idx'), models.Index(fields=['framework', 'priority_level'], name='compliance__framewo_f40cf1_idx'), models.Index(fields=['is_active', 'priority_score'], name='compliance__is_acti_9dc383_idx'), models.Index(fields=['organization', 'framework', 'priority_level'], name='compliance__organiz_a4df35_idx')],
                'unique_together': {('organization', 'framework', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('create_indicator', 'Create New Indicator'), ('enhance_data', 'Enhance Data Collection'), ('integrate_system', 'Integrate System/Data'), ('implement_process', 'Implement Process'), ('training', 'Training Required'), ('governance', 'Update Governance'), ('other', 'Other')], default='create_indicator', help_text='Type of recommendation', max_length=50)),
                ('title', models.CharField(help_text='Short title of recommendation', max_length=255)),
                ('description', models.TextField(help_text='Detailed recommendation description')),
                ('actionable_steps', models.JSONField(default=list, help_text='Array of specific steps to implement')),
                ('impact_score', models.FloatField(default=0.0, help_text='Expected impact on readiness score (0-10)')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Priority of this recommendation', max_length=20)),
                ('estimated_effort_days', models.IntegerField(default=0, help_text='Estimated implementation effort in days')),
                ('required_resources', models.TextField(blank=True, help_text='Resources/people needed to implement')),
                ('dependencies', models.JSONField(default=list, help_text='Requirements this depends on')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], db_index=True, default='pending', help_text='Current status of recommendation', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When implementation started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When recommendation was completed', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for compliance team')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When recommendation was generated')),
                ('framework', models.ForeignKey(help_text='Framework context', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='organizations.regulatoryframework')),
                ('organization', models.ForeignKey(help_text='Organization receiving recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_recommendations', to='organizations.organization')),
                ('requirement', models.ForeignKey(help_text='Requirement being addressed', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='compliance.frameworkrequirement')),
            ],
            options={
                'verbose_name': 'Compliance Recommendation',
                'verbose_name_plural': 'Compliance Recommendations',
                'db_table': 'compliance_recommendation',
                'ordering': ['-priority', '-impact_score', 'requirement__priority'],
                'indexes': [models.Index(fields=['organization', 'status'], name='compliance__organiz_94fcf7_idx'), models.Index(fields=['organization', 'priority'], name='compliance__organiz_639063_idx'), models.Index(fields=['framework', 'priority'], name='compliance__framewo_b9ba79_idx'), models.Index(fields=['status', 'priority', '-impact_score'], name='compliance__status_cd94ee_idx')],
                'unique_together': {('organization', 'framework', 'requirement', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='FrameworkReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_requirements', models.IntegerField(default=0, help_text='Total requirements in framework')),
                ('covered_requirements', models.IntegerField(default=0, help_text='Requirements with at least one indicator mapped')),
                ('coverage_percent', models.FloatField(default=0.0, help_text='Overall coverage percentage (0-100%)')),
                ('mandatory_requirements', models.IntegerField(default=0, help_text='Total mandatory requirements')),
                ('mandatory_covered', models.IntegerField(default=0, help_text='Mandatory requirements with coverage')),
                ('mandatory_coverage_percent', models.FloatField(default=0.0, help_text='Mandatory requirement coverage (0-100%)')),
                ('readiness_score', models.FloatField(default=0.0, help_text='Weighted readiness score: (mandatory * 0.7) + (optional * 0.3)')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Compliance risk level based on readiness', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Whether this is the current readiness assessment')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this assessment was last calculated')),
                ('framework', models.ForeignKey(help_text='Framework for assessment', on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to='organizations.regulatoryframework')),
                ('organization', models.ForeignKey(help_text='Organization being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='framework_readiness', to='organizations.organization')),
                ('reporting_period', models.ForeignKey(help_text='Reporting period for this assessment', on_delete=django.db.models.deletion.CASCADE, related_name='framework_readiness', to='submissions.reportingperiod')),
            ],
            options={
                'verbose_name': 'Framework Readiness',
                'verbose_name_plural': 'Framework Readiness Scores',
                'db_table': 'compliance_framework_readiness',
                'ordering': ['-calculated_at', 'framework__priority'],
                'indexes': [models.Index(fields=['organization', 'framework'], name='compliance__organiz_777cdc_idx'), models.Index(fields=['organization', 'risk_level'], name='compliance__organiz_2162f3_idx'), models.Index(fields=['framework', 'risk_level'], name='compliance__framewo_ffadab_idx'), models.Index(fields=['is_current', 'risk_level'], name='compliance__is_curr_0fb847_idx')],
                'unique_together': {('organization', 'framework', 'reporting_period')},
            },
        ),
    ]
