# Generated by Django 5.2.11 on 2026-03-28 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardmetric'),
        ('organizations', '0007_alter_businessunit_options_and_more'),
        ('submissions', '0005_rename_submissions_org_period_type_idx_submissions_organiz_6ac7d3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancesnapshot',
            options={'verbose_name': 'Compliance Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='dashboardsnapshot',
            options={'verbose_name': 'Dashboard Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='emissionsnapshot',
            options={'verbose_name': 'Emission Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='indicatorsnapshot',
            options={'verbose_name': 'Indicator Snapshot'},
        ),
        migrations.AlterModelOptions(
            name='targetsnapshot',
            options={'verbose_name': 'Target Snapshot'},
        ),
        migrations.RenameIndex(
            model_name='dashboardmetric',
            new_name='dashboard_d_organiz_c354d2_idx',
            old_name='dashboard_organiz_8e1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardmetric',
            new_name='dashboard_d_calcula_4a36c1_idx',
            old_name='dashboard_calculated_at_idx',
        ),
        migrations.AlterField(
            model_name='compliancesnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_snapshots', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='compliancesnapshot',
            name='snapshot_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compliancesnapshot',
            name='source',
            field=models.CharField(blank=True, help_text='Source or reason for snapshot (e.g., nightly_job, manual)', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashboardsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_snapshots', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='dashboardsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboardsnapshot',
            name='source',
            field=models.CharField(blank=True, help_text='Source or reason for snapshot (e.g., nightly_job, manual)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_snapshots', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='emissionsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emissionsnapshot',
            name='source',
            field=models.CharField(blank=True, help_text='Source or reason for snapshot (e.g., nightly_job, manual)', max_length=255),
        ),
        migrations.AlterField(
            model_name='indicatorsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_snapshots', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='indicatorsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indicatorsnapshot',
            name='source',
            field=models.CharField(blank=True, help_text='Source or reason for snapshot (e.g., nightly_job, manual)', max_length=255),
        ),
        migrations.AlterField(
            model_name='targetsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_snapshots', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='targetsnapshot',
            name='snapshot_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='targetsnapshot',
            name='source',
            field=models.CharField(blank=True, help_text='Source or reason for snapshot (e.g., nightly_job, manual)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='compliancesnapshot',
            index=models.Index(fields=['snapshot_date'], name='dashboard_c_snapsho_093a07_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancesnapshot',
            index=models.Index(fields=['organization', 'snapshot_date'], name='dashboard_c_organiz_22b809_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancesnapshot',
            index=models.Index(fields=['facility'], name='dashboard_c_facilit_209e55_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsnapshot',
            index=models.Index(fields=['snapshot_date'], name='dashboard_d_snapsho_a34206_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsnapshot',
            index=models.Index(fields=['organization', 'snapshot_date'], name='dashboard_d_organiz_77ca33_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardsnapshot',
            index=models.Index(fields=['facility'], name='dashboard_d_facilit_e7d718_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionsnapshot',
            index=models.Index(fields=['snapshot_date'], name='dashboard_e_snapsho_6b6576_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionsnapshot',
            index=models.Index(fields=['organization', 'snapshot_date'], name='dashboard_e_organiz_e0fca1_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionsnapshot',
            index=models.Index(fields=['facility'], name='dashboard_e_facilit_e4e690_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorsnapshot',
            index=models.Index(fields=['snapshot_date'], name='dashboard_i_snapsho_39fde6_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorsnapshot',
            index=models.Index(fields=['organization', 'snapshot_date'], name='dashboard_i_organiz_0eb04b_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatorsnapshot',
            index=models.Index(fields=['facility'], name='dashboard_i_facilit_33ab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsnapshot',
            index=models.Index(fields=['snapshot_date'], name='dashboard_t_snapsho_91ef43_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsnapshot',
            index=models.Index(fields=['organization', 'snapshot_date'], name='dashboard_t_organiz_b82571_idx'),
        ),
        migrations.AddIndex(
            model_name='targetsnapshot',
            index=models.Index(fields=['facility'], name='dashboard_t_facilit_2ac7e7_idx'),
        ),
    ]
