# Generated by Django 5.2.10 on 2026-02-08 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, help_text='JWT ID - unique identifier for this refresh token', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('revoked', models.BooleanField(db_index=True, default=False, help_text='Whether token has been revoked (logout, rotation, or security)')),
                ('replaced_by', models.UUIDField(blank=True, help_text='JTI of token that replaced this one (for rotation tracking)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where token was issued', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string where token was issued', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this refresh token', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_refresh_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked'], name='accounts_re_user_id_bfff6c_idx'), models.Index(fields=['expires_at'], name='accounts_re_expires_c42890_idx')],
            },
        ),
    ]
