# Generated by Django 5.2.10 on 2026-02-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverification',
            new_name='accounts_em_user_id_9edf3d_idx',
            old_name='accounts_ev_user_created_idx',
        ),
        migrations.AlterModelTable(
            name='emailverification',
            table=None,
        ),
    ]
