# Generated by Django on 2026-02-14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('accounts', '0004_rename_accounts_ev_user_created_idx_accounts_em_user_id_9edf3d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_otp', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='accounts.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_pa_user_created_idx')],
                'ordering': ['-created_at'],
            },
        ),
    ]
