# Generated by Django 5.2.10 on 2026-02-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordreset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordreset',
            new_name='accounts_pa_user_id_080f49_idx',
            old_name='accounts_pa_user_created_idx',
        ),
    ]
