# Generated by Django 5.2.11 on 2026-03-08 08:19

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_value', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'verbose_name': 'Calculated Emission',
                'verbose_name_plural': 'Calculated Emissions',
                'db_table': 'emissions_calculatedemission',
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('year', models.PositiveIntegerField()),
                ('factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('unit', models.CharField(help_text='Unit of factor, e.g. kgCO2e per liter', max_length=50)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'db_table': 'emissions_emissionfactor',
            },
        ),
    ]
