# Generated by Django 5.2.11 on 2026-03-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('emissions', '0001_initial'),
        ('organizations', '0003_rename_regulatory_coverage_to_primary_reporting_focus'),
        ('submissions', '0003_activitysubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedemission',
            name='activity_submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_emission', to='submissions.activitysubmission'),
        ),
        migrations.AddField(
            model_name='calculatedemission',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.facility'),
        ),
        migrations.AddField(
            model_name='calculatedemission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_emissions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='calculatedemission',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.reportingperiod'),
        ),
        migrations.AddField(
            model_name='calculatedemission',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.scope'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='calculatedemission',
            name='emission_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('activity_type', 'country', 'year')},
        ),
    ]
