# Generated by assistant
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('organizations', '0001_initial'),
        ('indicators', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('baseline_year', models.IntegerField()),
                ('baseline_value', models.FloatField()),
                ('target_year', models.IntegerField()),
                ('target_value', models.FloatField()),
                ('direction', models.CharField(default='decrease', max_length=16, choices=[('increase', 'Increase'), ('decrease', 'Decrease')])),
                ('status', models.CharField(default='active', max_length=16, choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=models.CASCADE, related_name='target_goals', to='organizations.organization')),
                ('indicator', models.ForeignKey(on_delete=models.PROTECT, related_name='target_goals', to='indicators.indicator')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='target_goals', to='organizations.facility')),
            ],
            options={
                'db_table': 'targets_targetgoal',
                'verbose_name': 'Target Goal',
                'verbose_name_plural': 'Target Goals',
            },
        ),
        migrations.CreateModel(
            name='TargetMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(db_index=True)),
                ('target_value', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=16, choices=[('pending', 'Pending'), ('achieved', 'Achieved'), ('at_risk', 'At Risk')])),
                ('goal', models.ForeignKey(on_delete=models.CASCADE, related_name='milestones', to='targets.targetgoal')),
            ],
            options={
                'db_table': 'targets_targetmilestone',
                'verbose_name': 'Target Milestone',
                'verbose_name_plural': 'Target Milestones',
            },
        ),
    ]
