# Generated by Django 5.2.11 on 2026-03-28 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_indicatorvalue'),
        ('organizations', '0007_alter_businessunit_options_and_more'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetmilestone',
            options={'ordering': ['year'], 'verbose_name': 'Target Milestone', 'verbose_name_plural': 'Target Milestones'},
        ),
        migrations.AlterField(
            model_name='targetgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='targetmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('achieved', 'Achieved'), ('at_risk', 'At Risk')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='targetgoal',
            index=models.Index(fields=['organization', 'status'], name='targets_tar_organiz_e3e214_idx'),
        ),
    ]
