# Generated by Django 5.2.11 on 2026-03-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_add_reporting_frequency'),
        ('targets', '0002_alter_targetmilestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgoal',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this target (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_goals', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='targetgoal',
            name='reporting_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], db_index=True, default='ANNUAL', help_text='Reporting frequency for this target (DAILY, WEEKLY, BI_WEEKLY, MONTHLY, QUARTERLY, SEMI_ANNUAL, ANNUAL)', max_length=20),
        ),
    ]
