# Generated by Django 5.2.10 on 2026-02-06 09:14

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('oil_gas', 'Oil & Gas'), ('finance', 'Finance')], max_length=50)),
                ('country', django_countries.fields.CountryField(help_text="Organization's country", max_length=2)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Sector-specific configuration (scopes, permits, frameworks)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations_organization',
                'indexes': [models.Index(fields=['sector', 'is_active'], name='organizatio_sector_e93b8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('facility_type', models.CharField(blank=True, help_text='e.g., Plant, Branch, Office, Refinery', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional facility-specific data')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'db_table': 'organizations_facility',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Optional contextual constraints (pillar, period, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_granted', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, help_text='Optional: scope membership to a specific facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='organizations.facility')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'organizations_membership',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_e0cddf_idx'), models.Index(fields=['user', 'is_active'], name='organizatio_user_id_9eceb5_idx')],
                'unique_together': {('user', 'organization', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_eb6f14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('organization', 'name')},
        ),
    ]
