# Generated by Django 5.2.10 on 2026-02-08 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='regulatory_coverage',
            field=models.CharField(choices=[('NIGERIA', 'Nigeria Regulators Only'), ('INTERNATIONAL', 'International Frameworks Only'), ('HYBRID', 'Nigeria + International (Hybrid)')], default='NIGERIA', help_text='Regulatory scope: Nigeria only, International only, or Hybrid', max_length=20),
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier (e.g., NESREA, GRI, ISSB)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full framework name', max_length=200)),
                ('jurisdiction', models.CharField(choices=[('NIGERIA', 'Nigeria'), ('INTERNATIONAL', 'International')], help_text='Regulatory jurisdiction', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Framework description and purpose')),
                ('sector', models.CharField(blank=True, help_text='Sector-specific framework (empty for cross-sector)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether framework is available for selection')),
                ('priority', models.IntegerField(default=0, help_text='Display/assignment priority (higher = more important)')),
            ],
            options={
                'verbose_name': 'Regulatory Framework',
                'verbose_name_plural': 'Regulatory Frameworks',
                'db_table': 'organizations_regulatory_framework',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['jurisdiction', 'is_active'], name='organizatio_jurisdi_e963f3_idx'), models.Index(fields=['sector', 'is_active'], name='organizatio_sector_ab0c47_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the organization's primary reporting framework")),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether framework is actively used')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When framework was assigned to organization')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this framework (null for system assignments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_assignments', to='organizations.organization')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='organizations.regulatoryframework')),
            ],
            options={
                'verbose_name': 'Organization Framework',
                'verbose_name_plural': 'Organization Frameworks',
                'db_table': 'organizations_organization_framework',
                'ordering': ['-is_primary', '-framework__priority', 'framework__name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='regulatory_frameworks',
            field=models.ManyToManyField(help_text='Assigned regulatory frameworks', related_name='organizations', through='organizations.OrganizationFramework', to='organizations.regulatoryframework'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['regulatory_coverage'], name='organizatio_regulat_a3ea33_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationframework',
            index=models.Index(fields=['organization', 'is_enabled'], name='organizatio_organiz_1558bb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationframework',
            index=models.Index(fields=['framework', 'is_enabled'], name='organizatio_framewo_c18119_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationframework',
            unique_together={('organization', 'framework')},
        ),
    ]
