# Generated by Django 5.2.10 on 2026-02-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_regulatory_coverage_regulatoryframework_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_regulat_a3ea33_idx',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='regulatory_coverage',
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_reporting_focus',
            field=models.CharField(choices=[('NIGERIA', 'Nigeria Regulators Only'), ('INTERNATIONAL', 'International Frameworks Only'), ('HYBRID', 'Nigeria + International (Hybrid)')], default='NIGERIA', help_text='Primary reporting focus: Nigeria only, International only, or Hybrid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['primary_reporting_focus'], name='organizatio_primary_c191cc_idx'),
        ),
    ]
