# Generated by Django 5.2.11 on 2026-03-15 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_rename_regulatory_coverage_to_primary_reporting_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='company_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-250 employees)'), ('large', 'Large (251-1000 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], help_text='Organization size category', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organization_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='registered_name',
            field=models.CharField(blank=True, help_text='Official registered company name', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=100),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish')], default='en', help_text='Primary system language', max_length=5)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Africa/Lagos', 'West Africa Time (WAT)'), ('Africa/Nairobi', 'East Africa Time (EAT)'), ('America/New_York', 'Eastern Standard Time (EST)'), ('America/Los_Angeles', 'Pacific Standard Time (PST)')], default='UTC', help_text='Organization timezone', max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand')], default='USD', help_text='Default currency for financial data', max_length=3)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'Day/Month/Year'), ('MM/DD/YYYY', 'Month/Day/Year'), ('YYYY-MM-DD', 'Year-Month-Day')], default='DD/MM/YYYY', help_text='Date display format', max_length=20)),
                ('admin_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', help_text='Admin interface theme', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Enable system notifications')),
                ('system_update_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often to check for system updates', max_length=20)),
                ('security_checks_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often to run security checks', max_length=20)),
                ('export_formats', models.JSONField(blank=True, default=list, help_text="Allowed export formats (e.g., ['pdf', 'xlsx', 'csv'])")),
                ('require_2fa', models.BooleanField(default=False, help_text='Require two-factor authentication for all users')),
                ('encrypt_stored_data', models.BooleanField(default=False, help_text='Encrypt sensitive data at rest')),
                ('encryption_method', models.CharField(choices=[('AES-256', 'AES-256'), ('AES-128', 'AES-128'), ('RSA-2048', 'RSA-2048')], default='AES-256', help_text='Encryption algorithm for stored data', max_length=20)),
                ('organization', models.OneToOneField(help_text='Organization these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='system_settings', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organizations_settings',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Department code/abbreviation', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether department is active')),
                ('organization', models.ForeignKey(help_text='Organization this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'organizations_department',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_1acc94_idx')],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
