# Generated by Django 5.2.11 on 2026-03-28 12:26

import django.db.models.deletion
import organizations.models.organization
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_convert_profile_and_businessunit_to_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name': 'Business Unit', 'verbose_name_plural': 'Business Units'},
        ),
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'verbose_name': 'Organization Profile', 'verbose_name_plural': 'Organization Profiles'},
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(help_text='Business unit name', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='organization',
            field=models.ForeignKey(help_text='Organization this business unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='settings',
            field=models.JSONField(blank=True, default=organizations.models.organization.Organization._default_settings, help_text='Sector-specific configuration (scopes, permits, frameworks)'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='cac_document',
            field=models.FileField(blank=True, help_text='Uploaded CAC registration document', null=True, upload_to='organization_documents/'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='cac_registration_number',
            field=models.CharField(blank=True, help_text='Company registration number (CAC)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-250 employees)'), ('large', 'Large (251-1000 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], help_text='Organization size category', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='fiscal_year_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fiscal year end month (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Fiscal year start month (1-12)', null=True),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='organization_logos/'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='operational_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of operational locations'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(help_text='Organization this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='registered_business_name',
            field=models.CharField(blank=True, help_text='Official registered business name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='auto_compliance_enabled',
            field=models.BooleanField(default=False, help_text='Whether automatic compliance checks are enabled'),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='global_reporting_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', help_text='Global reporting frequency', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='local_reporting_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Local reporting frequency', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='businessunit',
            unique_together={('organization', 'name')},
        ),
    ]
