# Generated by Django 5.2.11 on 2026-03-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_add_department_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='organizatio_organiz_baf8f9_idx',
            old_name='organizations_organiz_6b8afd_idx',
        ),
    ]
