# Generated by Django 5.2.11 on 2026-04-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_add_organization_hierarchy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_organiz_d4294a_idx',
            old_name='organizations_organizatio_type_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_parent__485487_idx',
            old_name='organizations_parent_type_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='organizatio_parent__c2cd70_idx'),
        ),
    ]
